export default {
  GET_FILE_LIST: 'GET_FILE_LIST',
  BUSINESS_ENTITY_LIST_RECEIVED: 'GET_FILE_RECEIVED',
  GET_BUSINESS_ENTITY_LIST_ERROR: 'GET_FILE_LIST_ERROR',
  GET_SCAN_DEVICE: 'GET_SCAN_DEVICE',
  IMAGE_FILE_SCANNED: 'IMAGE_FILE_SCANNED',
  SCAN_IMAGE_FILE_FAILED: 'SCAN_IMAGE_FILE_FAILED',
  UPLOAD_TO_GW: 'UPLOAD_TO_GW',
  UPLOAD_TO_GW_SUCCESS: 'UPLOAD_TO_GW_SUCCESS',
  UPLOAD_TO_GW_FAILED: 'UPLOAD_TO_GW_FAILED',
  GET_CLIENT_LIST_SUCCESS: 'GET_CLIENT_LIST_SUCCESS',
  GET_CLIENT_LIST_FAILED: 'GET_CLIENT_LIST_FAILED',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REQUEST_LOGIN: 'REQUEST_LOGIN'
};
